;READ A CHARACTER. IF IT IS 'y' OR 'Y',DISPLAY IT; OTHERWISE,TERMINATE THE PROGRAM
INCLUDE "EMU8086.INC"
.MODEL SMALL
.STACK 100H
.CODE
MAIN PROC
    MOV AH,1
    INT 21H
    PRINTN ""
    CMP AL,'Y'
    JE INS1
    CMP AL,'y'
    JE INS1
    JMP EXIT
    
    INS1:
        MOV AH,2
        MOV DL,AL
        INT 21H
    EXIT:
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN